### ISSUE TITLE
Trailheads without trails are throwing an error

### ISSUE THREAD

**Issue by anselmbradford** [opentraildata/OpenTrails-Mobile#84]
Find the marker southwest of Green, OH. and click it.
![screen shot 2014-04-28 at 3 33 10 pm](https://cloud.githubusercontent.com/assets/704760/2823789/1d327214-cf25-11e3-914f-f2607d4d2a4c.png)

The following error is thrown and no trails view appears.

```
TypeError: Cannot read property 'photo' of undefined
    at selectTrailHead (http://localhost:8000/ios/www/js/application/controllers.js:262:52)
    at http://localhost:8000/ios/www/js/application/controllers.js:243:39
    at h.$eval (http://localhost:8000/ios/www/js/lib/angular/angular.min.js:104:370)
    at h.$apply (http://localhost:8000/ios/www/js/lib/angular/angular.min.js:105:121)
    at h.$delegate.__proto__.$apply (<anonymous>:855:30)
    at onTrailHeadMarkerClick (http://localhost:8000/ios/www/js/application/controllers.js:243:18)
    at null.<anonymous> (http://localhost:8000/ios/www/js/application/controllers.js:252:13)
    at o.Mixin.Events.fireEvent (http://localhost:8000/ios/www/js/lib/leaflet/leaflet.js:6:4952)
    at o.Marker.o.Class.extend._onMouseClick (http://localhost:8000/ios/www/js/lib/leaflet/leaflet.js:7:17248)
    at HTMLImageElement.t.(anonymous function).s [as _leaflet_click2276] (http://localhost:8000/ios/www/js/lib/leaflet/leaflet.js:8:20284) 
```

According to @alanjosephwilliams this is because this is a trailhead without any trails attached to it.

**Comment by lovehandle** [comment]
Makes sense. I'll address this as I refactor the controllers/view logic into their own separate modules.
